- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: cloud-shell-storage-eastus
      location: eastus
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: cloud-shell-storage-eastus
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: cloud-shell-storage-eastus
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: cloud-shell-storage-eastus
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: cloud-shell-storage-eastus
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: cloud-shell-storage-eastus
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: cloud-shell-storage-eastus
      name: myVM
      vm_size: Standard_DS1_v2
      admin_username: mhughes
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/mhughes/.ssh/authorized_keys
          key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCudQfZCmINpd6OSUihsLxVIl6h8OsxL/FTqBCcMT7NfqmZYJgPJYLCloGKJqTRJobfNKKGGcr1+vzYxIqeRu1JuC6DTWliWDTYX9T1+Y2RL09gzqdEvQjSY+bYTR6JgYtCbpSszX6gFad1Q0c5qzCjOEf9RKayP8ouNipivf8OqXF6xI1I3y6mLFrNQpKe/k0MdAxoDyd68iyYegJPgfR58DWmsqhkbn/jaTrXJjrmMW6hBCx1XF1SPkGAjw4tSHrOxOZBKKQlSGm3RuAqQ98slYiqzo253K55PhF6eRyxEYq6tjse0VPqwMpb7QkSll6aVqW61iC+svN5D9L8ROOR azureuser@cc-f99470df-9f56d9cb8-p995j
      network_interfaces: myNIC
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: '2016-Datacenter'
        version: latest
