
---
- name: Find the demo.txt file
  hosts: all
  
  tasks:
  - name: Find files and do not return the checksum
    win_find:
       paths: C:\Users\Administrator\Desktop\
       file_type: file
       recurse: yes
       get_checksum: no
      
