
---
- name: Find the demo.txt file
  hosts: all
  #become_method: runas
  
  tasks:
  - name: Find file
    win_find:
      paths: 'c:\Users\Administrator\Desktop\test.txt'
      recurse: yes
      file_type: file
      
