
---
- name: Find the demo.txt file
  hosts: all
  #become_method: runas
  
  tasks:
  - name: Find files and do not return the checksum
    win_find:
       paths: C:\Users\Administrator\Desktop\test.txt.txt
       file_type: file
       #recurse: yes
       #get_checksum: no
      
