---
- name: Move the Demo.txt file to Windows Host
  hosts: all
  become: True
  
  tasks:
  - name: Move File
    win_copy:
      src: /home/ec2-user/myplatform/ansible/Demo.txt
      dest: c:\Users\Administrator\Desktop\
      remote_src: no
