---
- name: Move the Demo.txt file to Windows Host
  hosts: all
  become: True
  
  tasks:
  - name: Move File
    win_copy:
      src: C:\Users\Administrator\Desktop\test.txt
      dest: C:\Users\Administrator\Desktop\demo.txt
      remote_src: yes
