---
- name: Move the demo.txt file to Windows Host
  hosts: all
  become_method: runas
  
  tasks:
  - name: Move File
    win_copy:
      src: /home/ec2-user/vhosts.conf
      dest: c:\Users\Administrator\Desktop\demo.conf
      remote_src: no

   # become_password: M.Rr@GoL)HJmOBCoFtwl-D%Ah!2*Atu?
