---
- name: Move the demo.txt file to Windows Host
  hosts: all
  become_method: runas
  
  tasks:
- name: Download file from FTP with authentication
  win_get_url:
    url: ftp://18.237.243.155/test.txt
    dest: 'c:\Users\Administrator\Desktop\
