---
- name: Move the demo.txt file to Windows Host
  hosts: all
  become_method: runas
  remote_user: Administrator
  
  tasks:
  
  - name: grant the ansible user the SeTcbPrivilege right
    win_user_right:
      name: SeTcbPrivilege
      users: Administrator
      action: add

  - name: Move File
    win_copy:
      src: /home/ec2-user/demo.txt
      dest: c:\Users\Administrator\Desktop\demo.txt
      remote_src: no
