---
- name: Move the demo.txt file to Windows Host
  hosts: all
  
  tasks:
  - name: Move File
    win_copy:
      src: /home/ec2-user/demo.txt
      dest: c:\Users\Administrator\Desktop\demo.txt
      remote_src: no
    become: yes
    become_mehtod: runas
    become_user: Administrator
    become_password: M.Rr@GoL)HJmOBCoFtwl-D%Ah!2*Atu?
