---
- name: Provisioning ec2 instance
  hosts: localhost
  connection: local
  vars:
    Instance_name: fhcdbsumt02
  tasks:
  - name: Launch ec2 Instance
    ec2:
      key_name: fhlbckey
      region: us-east-2
      #group: databases
      instance_type: t2.micro
      #image: ami-04be6a27b0206807f
      image: ami-0cd3dfa4e37921605
      wait: yes
      #wait_timeout: 500
      count: 1
      vpc_subnet_id: subnet-ed86bf85
      assign_public_ip: yes
      instance_tags:
         BusinessService: BusService
         Application: TestApp
         Env: DEV
         Name: "{{ Instance_name }}"
         Owner: JSMITH
         Patch Group: Patch1
      #volumes:
       # - device_name: /dev/sda1
          #volume_type: gp2
          #volume_size: 100
          #delete_on_termination: true
          #ec2_tags:
            #tags:
              #Name: testingVolTags
              #Testing: Here
      #monitoring: yes
      #vpc_subnet_id: subnet-ed86bf85
      
    register: result
   
  - debug:
      var=result
  - debug:
      var=result.instances.block_device_mapping[0].volume_id
  
  
  - name: Add tags to Volume
    ec2_tag:
      region: us-east-2
      resource: result.instances.block_device_mapping[0].volume_id
      state: absent
      tags:
        Name: TestApp
        Drive: root
        Env: DEV
        Name: fhcdbsumt02  
  
  - name: create alarm
    ec2_metric_alarm:
      state: present
      region: us-east-2
      name: "{{ Instance_name }}_NoAutorecover-statuscheck_instance-{{ result.instance_ids }}"
      metric: "StatusCheckFailed"
      namespace: "AWS/EC2"
      statistic: Average
      comparison: "<="
      threshold: 1.0
      period: 60
      evaluation_periods: 8
      #unit: "Percent"
      description: "Status check alarm"
      dimensions: {'InstanceId' : '{{ result.instance_ids }}'}
      alarm_actions: ['arn:aws:sns:us-east-2:935659307200:NotificationTopicEC2']
      
      
      

 # - name: Add tags to Volume
   # ec2_tag:
     # region: us-east-2
    #  resource: result.instances.volume_id
     # state: absent
      #tags:
       # Name: TestApp
        #Drive: root
        #Env: DEV
       # Name: fhcdbsumt02
        
