---
- name: Provisioning ec2 instance
  hosts: localhost
  connection: local
  tasks:
  - name: Launch ec2 Instance
    ec2:
      key_name: fhlbckey
      region: us-east-2
      #group: databases
      instance_type: t2.micro
      image: ami-04be6a27b0206807f
      #image: ami-0cd3dfa4e37921605
      wait: yes
      #wait_timeout: 500
      count: 1
      vpc_subnet_id: subnet-ed86bf85
      assign_public_ip: yes
      instance_tags:
         BusinessService: BusService
         Application: TestApp
         Env: DEV
         Name: fhcdbsumt02
         Owner: JSMITH
         Patch Group: Patch1
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 8
          delete_on_termination: true
          tags:
            Name: testingVolTags
      monitoring: yes
      #vpc_subnet_id: subnet-ed86bf85
      
    register: result
   
  - debug:
      var=result

 # - name: Add tags to Volume
   # ec2_tag:
     # region: us-east-2
    #  resource: result.instances.volume_id
     # state: absent
      #tags:
       # Name: TestApp
        #Drive: root
        #Env: DEV
       # Name: fhcdbsumt02
        
