---
- name: RHEL Server Inital Configuration
  hosts: all
  #ansible_ssh_user=ec2-user
  become: yes
  become_method: sudo
  tasks:
    - name: Commit changes to made in the SSH daemon configuration
      expect:
        command: service sshd reload
