---
- name: Provisioning ec2 instance
  hosts: localhost
  connection: local
  tasks:
  - name: Tagging and CloudWatch
    ec2:
      key_name: fhlbckey
      region: us-east-2
      group: databases
      instance_type: t2.micro
      image: ami-04be6a27b0206807f
      wait: yes
      wait_timeout: 500
      count: 5
      instance_tags:
         db: postgres
      monitoring: yes
      vpc_subnet_id: subnet-ed86bf85
      assign_public_ip: yes
