---
- name: Provisioning ec2 instance
  hosts: localhost
  connection: local
  vars:
    aws_region: us-east-2a
    resource_name: fhcdbsumt02
    instance_type: t2.micro
    key_name: fhlbckey
    subnet_name: subnet-ed86bf85
    security_group: sg-079c52d7e252b845d
    Environemnt: Test
    ec2_ami_image: ami-04be6a27b0206807f
    region: us-east-2
    Application_Name: TestApp
  tasks:
  - name: New instance with Public IP
    ec2_instance:
    #profile:
      region: "{{ aws_region }}"
      name: "{{ resource_name }}"
      key_name: "{{ key_name }}"
      vpc_sub_net: "{{ subnet_name }}"
      security_group: "{{ security_group }}"
      network:
        assign_public_ip: true
      image_id: " {{ ec2_ami_image[aws_region] }}"
      tags:
        Name: "{{ resource_name }}"
        Env: "{{ Environemnt }}"
        Drive: root
        Application: "{{ Application_Name }}"
   # register: in_default_vpc
  # - debug: in_default_vpc
